baseURL: "https://afbat.co"
title: Ava Francesca Battocchio
buildFuture: true 
pagination:
  pagerSize: 5
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
taxonomies:
    tag: tags
menu:
    main:
        - name: About
          url: /about/
          weight: 1
        - name: Papers
          url: /papers/
          weight: 2
        - name: Public Scholarship
          url: /public-scholarship/
          weight: 3
        - name: CV
          url: /cv.pdf
          weight: 4
        #- name: Design
        #  url: /design/
        #  weight: 3  
        #- name: Projects
        #  url: /projects/
        #  weight: 4
        - name: Media
          url: /media/
          weight: 5
        - name: Updates
          url: /blog/
          weight: 6
 
params:
    description: "Ava Francesca Battocchio is an Assistant Professor of Journalism at Northwestern University's Medill School, specializing in community information systems and rural media environments."
    author: Ava Francesca Battocchio
    env: production
    #googleAnalyticsID: "G-"
    DateFormat: "January 2006"
    hideFooter: true
    defaultTheme: dark
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    #hidemeta: true
    profileMode:
        enabled: true
        title: Ava Francesca Battocchio
        subtitle: >
            Hiya! My name is Ava Francesca and I'm an Assistant Professor of Journalism at [Northwestern University's Medill School](https://www.medill.northwestern.edu/), where I specialize in community information systems and rural media environments. I completed my PhD in Information and Media from Michigan State University in 2025.<br><br>
            My research focuses on how residents in rural, remote, and post-industrial communities learn about public issues amidst changing technology, digital access disparities, and shifting local news environments. Through this work, I examine how place identity shapes critical information access and dissemination.
        imageUrl: "/picture.png"
        imageWidth: 160
        imageHeight: 160
        imageTitle: Ava Francesca Battocchio
        buttons:
          - name: About
            url: /about/
          - name: Papers
            url: /papers/
          - name: Public Scholarship
            url: /public-scholarship/
          - name: CV
            url: /cv.pdf
          #- name: Design
          #  url: /design/
          #- name: Projects
          #  url: /projects/
          - name: Tags
            url: /tags/
          - name: Updates
            url: /blog/
    socialIcons:
        #- name: CV
        #  url: /cv.pdf
        - name: Email
          url: mailto:afbat@northwestern.edu
        #- name: Location
        #  url: /location/
        #- name: Office Hours
        #  url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=JuKCgpcAAAAJ&hl
        - name: GitHub
          url: https://github.com/afbat
        - name: LinkedIn
          url: https://www.linkedin.com/in/afbattocchio/
        #- name: Twitter
        #  url: https://twitter.com/_afbat
        - name: ORCID
          url: https://orcid.org/0000-0003-4950-5782
    assets:
        css: ["css/northwestern-theme.css"]
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
        text: "Ava Francesca Battocchio"
        icon: /favicon.ico
        iconHeight: 18
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: modus-operandi
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
